backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;

blur:
{
  method = "dual_kawase";
  strength = 3;
};

blur-background-exclude = [
  "name = 'Dunst'",
  "name = 'firefox'",
  "name = 'zen'",
  "name = 'cava'",
  "name = 'peek'",
  "name = 'bitwarden'"
];

opacity-rule = [
    "70:class_g = 'com.github.th_ch.youtube_music' && focused",
    "60:class_g = 'com.github.th_ch.youtube_music' && !focused"
];

