" Minimal config, compatible with system default vim installations.

" vi compatible mode
set nocompatible

" filetype support
filetype on
filetype plugin on
filetype indent on
syntax on

" line numbers
set number
set relativenumber

" cursor
"set cursorline
"set cursorcolumn
set scrolloff=8

" tabs and spaces
set shiftwidth=2
set tabstop=2
set expandtab  " use space instead of tab

" other
set nowrap

if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

