#!/usr/bin/env bash

STATE_DIR="$HOME/.local/state/ambi3nce/"
SOCK_FILE="$STATE_DIR/mpv_socks"
BACKGROUND_DIR="$HOME/.local/share/backgrounds/"

if [ ! -f "$SOCK_FILE" ]; then
  echo "Sockets file does not exist: $SOCK_FILE"
  exit 1
fi

SOCKS=($(<"$SOCK_FILE"))

if [ "${#SOCKS[@]}" -eq 0 ]; then
  echo "No sockets found in $SOCK_FILE"
  exit 1
fi

FIRST="${SOCKS[0]}"

# Check each socket exists
for s in "${SOCKS[@]}"; do
  if [ ! -e "$s" ]; then
    echo "Socket $s does not exist"
    exit 1
  fi
done

choice=$(printf "Play/Pause\nMute/Unmute\nVolume 25\nVolume 50\nVolume 100\nSelect File" | rofi -dmenu -i -p "Wallpaper Control")

case "$choice" in
  "Play/Pause")
    for s in "${SOCKS[@]}"; do
      echo '{ "command": ["cycle", "pause"] }' | socat - "$s"
    done
    ;;
  "Mute/Unmute")
    echo '{ "command": ["cycle", "mute"] }' | socat - "$FIRST"
    ;;
  "Volume 25")
    echo '{ "command": ["set_property", "volume", 25] }' | socat - "$FIRST"
    ;;
  "Volume 50")
    echo '{ "command": ["set_property", "volume", 50] }' | socat - "$FIRST"
    ;;
  "Volume 100")
    echo '{ "command": ["set_property", "volume", 100] }' | socat - "$FIRST"
    ;;
  "Select File")
    SELECTED="$("$HOME/.config/rofi/scripts/rofi-select-file-from-dir" "$BACKGROUND_DIR" 'Select Wallpaper' 'mp4')"
    if [ -n "$SELECTED" ]; then
        ln -sf "$SELECTED" "$STATE_DIR/current_wallpaper"
        "$HOME/.config/i3/scripts/launch_xwinwrap.sh"
    fi
    ;;
esac

